name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

<<<<<<< HEAD

=======
>>>>>>> main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
=======
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
>>>>>>> main
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1
        with:
<<<<<<< HEAD
          arguments: build
=======
          arguments: build
>>>>>>> main
